version: '3'
services:
    vpn:
        networks:
            wg-vpn:
        image: thrnz/docker-wireguard-pia
        volumes:
            - pia:/pia
            # Forwarded port is dumped to /pia-shared/port.dat for potential use in other containers
            #- pia-shared:/pia-shared
        # privileged is needing for adding 0.0.0.0/0 route
        privileged: true
        cap_add:
            - NET_ADMIN
            # Still needed with 5.6+ kernel?
            - SYS_MODULE
        environment:
            #- LOCAL_NETWORK=192.168.1.0/24
            #- ALLOW_DOCKER=1
            - LOC=swiss
            - USER=p0000000
            - PASS=xxxxxxxxxxxxxxxx
            #- KEEPALIVE=25
            #- VPNDNS=8.8.8.8,8.8.4.4
            #- USEMODERN=1
            #- PORT_FORWARDING=0
        sysctls:
            - net.ipv6.conf.default.disable_ipv6=1
            - net.ipv6.conf.all.disable_ipv6=1
            - net.ipv6.conf.lo.disable_ipv6=1

volumes:
    pia:
    pia-shared:
    
networks:
    wg-vpn: