version: '3'
services:
    vpn:
        networks:
            wg-vpn:
        image: thrnz/docker-wireguard-pia
        volumes:
            - pia:/pia
            # Forwarded port is dumped to /pia-shared/port.dat for potential use in other conainers
            #- pia-shared:/pia-shared
        privileged: true
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        environment:
            #- LOCAL_NETWORK=192.168.1.1/24
            #- ALLOW_DOCKER=1
            - LOC=swiss
            - USER=p0000000
            - PASS=xxxxxxxxxxxxxxxx
            #- KEEPALIVE=25
            #- VPNDNS=8.8.8.8,8.8.4.4
            #- USEMODERN=1
            #- PORT_FORWARDING=0

volumes:
    pia:
    pia-shared:
    
networks:
    wg-vpn: